version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17
  pre_build:
    commands:
      - echo Nothing to do in the pre_build phase...
  build:
    commands:
      - echo Build started on `date`
      - mvn install
      - mv target/AWS-Demo-0.0.1-SNAPSHOT.jar AWS-Demo-0.0.1-SNAPSHOT.jar
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - AWS-Demo-0.0.1-SNAPSHOT.jar